# coding: utf-8

# flake8: noqa

"""
    Task Management System

    A robust Task Management API with strict status transition enforcement.  ## Status Transition Rules Tasks must follow this exact order: - `pending` → `in-progress` → `completed`  Skipping steps (e.g., `pending` → `completed`) is **not allowed**. Downgrading status (e.g., `completed` → `in-progress`) is **not allowed**.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "TasksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "LocationInner",
    "TaskCreate",
    "TaskListResponse",
    "TaskResponse",
    "TaskStatus",
    "TaskUpdate",
    "ValidationError",
]

# import apis into sdk package
from .api_client import ApiClient
from .configuration import Configuration
from task_sdk.api.health_api import HealthApi as HealthApi
from task_sdk.api.tasks_api import TasksApi as TasksApi

# import ApiClient
from task_sdk.api_response import ApiResponse as ApiResponse
from task_sdk.api_client import ApiClient as ApiClient
from task_sdk.configuration import Configuration as Configuration
from task_sdk.exceptions import OpenApiException as OpenApiException
from task_sdk.exceptions import ApiTypeError as ApiTypeError
from task_sdk.exceptions import ApiValueError as ApiValueError
from task_sdk.exceptions import ApiKeyError as ApiKeyError
from task_sdk.exceptions import ApiAttributeError as ApiAttributeError
from task_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from task_sdk.models.http_validation_error import HTTPValidationError as HTTPValidationError
from task_sdk.models.location_inner import LocationInner as LocationInner
from task_sdk.models.task_create import TaskCreate as TaskCreate
from task_sdk.models.task_list_response import TaskListResponse as TaskListResponse
from task_sdk.models.task_response import TaskResponse as TaskResponse
from task_sdk.models.task_status import TaskStatus as TaskStatus
from task_sdk.models.task_update import TaskUpdate as TaskUpdate
from task_sdk.models.validation_error import ValidationError as ValidationError

