# coding: utf-8

"""
    Task Management System

    A robust Task Management API with strict status transition enforcement.  ## Status Transition Rules Tasks must follow this exact order: - `pending` → `in-progress` → `completed`  Skipping steps (e.g., `pending` → `completed`) is **not allowed**. Downgrading status (e.g., `completed` → `in-progress`) is **not allowed**.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from task_sdk.models.task_list_response import TaskListResponse

class TestTaskListResponse(unittest.TestCase):
    """TaskListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskListResponse:
        """Test TaskListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskListResponse`
        """
        model = TaskListResponse()
        if include_optional:
            return TaskListResponse(
                total = 56,
                tasks = [
                    task_sdk.models.task_response.TaskResponse(
                        id = 56, 
                        title = '', 
                        description = '', 
                        status = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return TaskListResponse(
                total = 56,
                tasks = [
                    task_sdk.models.task_response.TaskResponse(
                        id = 56, 
                        title = '', 
                        description = '', 
                        status = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testTaskListResponse(self):
        """Test TaskListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
