# coding: utf-8

# flake8: noqa
"""
    Task Management System

    A robust Task Management API with strict status transition enforcement.  ## Status Transition Rules Tasks must follow this exact order: - `pending` → `in-progress` → `completed`  Skipping steps (e.g., `pending` → `completed`) is **not allowed**. Downgrading status (e.g., `completed` → `in-progress`) is **not allowed**.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from task_sdk.models.http_validation_error import HTTPValidationError
from task_sdk.models.location_inner import LocationInner
from task_sdk.models.task_create import TaskCreate
from task_sdk.models.task_list_response import TaskListResponse
from task_sdk.models.task_response import TaskResponse
from task_sdk.models.task_status import TaskStatus
from task_sdk.models.task_update import TaskUpdate
from task_sdk.models.validation_error import ValidationError

