"""
    Task Management System

    A robust Task Management API with strict status transition enforcement.  ## Status Transition Rules Tasks must follow this exact order: - `pending` → `in-progress` → `completed`  Skipping steps (e.g., `pending` → `completed`) is **not allowed**. Downgrading status (e.g., `completed` → `in-progress`) is **not allowed**.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "task-sdk"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Task Management System",
    author="Task Management API",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Task Management System"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    A robust Task Management API with strict status transition enforcement.  ## Status Transition Rules Tasks must follow this exact order: - &#x60;pending&#x60; → &#x60;in-progress&#x60; → &#x60;completed&#x60;  Skipping steps (e.g., &#x60;pending&#x60; → &#x60;completed&#x60;) is **not allowed**. Downgrading status (e.g., &#x60;completed&#x60; → &#x60;in-progress&#x60;) is **not allowed**.
    """,  # noqa: E501
    package_data={"task_sdk": ["py.typed"]},
)
